### ISSUE TITLE
put SHA-1 in build

### ISSUE THREAD

**Issue by nuborisar** [red-panda-ci/jenkins-pipeline-library#2]

**Comment by pedroamador** [comment]
There's part of an informative html that attach to the builds as changelog report is attached.
Information to be place in the report (won't translate):
* si tiene servicios sticky(debe probarse el reinicio,en dif fases del flow)
* leer si tiene allowbackup, esto si el tlf tiene drive activado guarda preferences y todo elnlocal en red, desintalar e instalar xa ver si borra bien los datos
* leer si tiene pushes
* leer si tiene intents filter y diseñar prueba de apertura de tipos de archivo,deeplinks
* leer  api max min(probar en telefono 23 una app de 22
